### ISSUE TITLE
Add Maximum subarray

### ISSUE THREAD

**Issue by DurveshKumarPal** [DurveshKumarPal/ZERO-TO-FAANG-ASSIGNMENT-SOLUTION#2]
Add Leetcode problem 
## Maximum Subarry
[Problem]( https://leetcode.com/problems/maximum-subarray/)

**Comment by nirajacharyaa** [comment]
hey, can you label your repository as hacktoberfest you will get many pull requests.

**Comment by nirajacharyaa** [comment]
I will take over this issue after you label it hacktoberfest.

**Comment by DurveshKumarPal** [comment]
@nirajacharyaa sure bro.

**Comment by nirajacharyaa** [comment]
done @DurveshKumarPal  bro but the label should be `hacktoberfest`  you can edit that. If you want to contribute to my Javascript project feel free.
