### ISSUE TITLE
Rotate array

### ISSUE THREAD

**Issue by DurveshKumarPal** [DurveshKumarPal/ZERO-TO-FAANG-ASSIGNMENT-SOLUTION#6]
Array medium level Leetcode problem 
  (Rotate Array)

[Problem](https://leetcode.com/problems/rotate-array/)

**Comment by Kanika2772002** [comment]
Array medium level Leetcode problem( #7 )

**Comment by DurveshKumarPal** [comment]
@Kanika2772002 thanks for your contribution.
